FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/node:20.11.1-slim as build

WORKDIR /zklink-l3summit-web

RUN apt update -y

RUN apt install -y python-is-python3

ADD . /zklink-l3summit-web

RUN yarn && yarn build

FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:alpine3.18

RUN mkdir /build

COPY --from=build /zklink-l3summit-web/build /build

CMD ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
